# -*- coding: utf-8 -*-
"""model_util.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tGF_a97DW0WxnGEznxFQrj_KrsEwipgE
"""

import tensorflow as tf
from tensorflow.keras.layers import Layer
import tensorflow.keras.backend as K

# 必須包含自定義層，否則 load_model 會失敗
class AttentionLayer(Layer):
    def __init__(self, **kwargs):
        super(AttentionLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        self.W = self.add_weight(name="att_weight", shape=(input_shape[-1], 1), initializer="glorot_uniform")
        self.b = self.add_weight(name="att_bias", shape=(input_shape[1], 1), initializer="zeros")
        super(AttentionLayer, self).build(input_shape)

    def call(self, x):
        e = K.dot(x, self.W) + self.b
        e = K.tanh(e) * 5.0
        a = K.softmax(e, axis=1)
        output = x * a
        return K.sum(output, axis=1), a

    def get_config(self):
        return super(AttentionLayer, self).get_config()